name: Build Docker

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        dockerfile: ['grapejuice']
    steps:
      - 
        name: Tailscale
        uses: tailscale/github-action@main
        with:
          version: '1.42.0'
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --login-server ${{ secrets.TAILSCALE_LOGINSERVER }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Wait for Registry
        run: curl -s -o /dev/null -w "%{http_code}" -m 30 https://${{ secrets.REGISTRY_HOST }}
      -
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          file: dockerfile-${{ matrix.dockerfile }}
          push: true
          tags: ${{ secrets.REGISTRY_HOST }}/${{ secrets.IMAGE_TAG_USER }}/kasm-${{ matrix.dockerfile }}:latest
